const listProducts = [
  {
    id: "1",
    Modelo: "S60",
    Marca: "Volvo",
    Año: 2002,
    Stock: 13,
    Precio: "$26468.99",
    Color: "Blue",
    img: "http://dummyimage.com/604x510.png",
    Category: "Collections",
  },
  {
    id: "2",
    Modelo: "612 Scaglietti",
    Marca: "Ferrari",
    Año: 2007,
    Stock: 20,
    Precio: "$29780.04",
    Color: "Orange",
    img: "http://dummyimage.com/602x658.png",
    Category: "Collections",
  },
  {
    id: "3",
    Modelo: "Ridgeline",
    Marca: "Honda",
    Año: 2007,
    Stock: 12,
    Precio: "$23026.27",
    Color: "Blue",
    img: "http://dummyimage.com/599x654.png",
    Category: "Collections",
  },
  {
    id: "4",
    Modelo: "Express 2500",
    Marca: "Chevrolet",
    Año: 2004,
    Stock: 16,
    Precio: "$35625.38",
    Color: "Purple",
    img: "http://dummyimage.com/575x661.png",
    Category: "News",
  },
  {
    id: "5",
    Modelo: "Sentra",
    Marca: "Nissan",
    Año: 2005,
    Stock: 19,
    Precio: "$48367.96",
    Color: "Yellow",
    img: "http://dummyimage.com/659x578.png",
    Category: "Collections",
  },
  {
    id: "6",
    Modelo: "Escalade EXT",
    Marca: "Cadillac",
    Año: 2010,
    Stock: 14,
    Precio: "$47671.85",
    Color: "Purple",
    img: "http://dummyimage.com/552x523.png",
    Category: "Collections",
  },
  {
    id: "7",
    Modelo: "Parisienne",
    Marca: "Pontiac",
    Año: 1985,
    Stock: 11,
    Precio: "$17174.57",
    Color: "Blue",
    img: "http://dummyimage.com/638x591.png",
    Category: "News",
  },
  {
    id: "8",
    Modelo: "98",
    Marca: "Oldsmobile",
    Año: 1996,
    Stock: 14,
    Precio: "$16151.79",
    Color: "Indigo",
    img: "http://dummyimage.com/686x662.png",
    Category: "Collections",
  },
  {
    id: "9",
    Modelo: "XJ Series",
    Marca: "Jaguar",
    Año: 2000,
    Stock: 14,
    Precio: "$33884.81",
    Color: "Violet",
    img: "http://dummyimage.com/607x659.png",
    Category: "Collections",
  },
  {
    id: "10",
    Modelo: "612 Scaglietti",
    Marca: "Ferrari",
    Año: 2010,
    Stock: 14,
    Precio: "$34158.68",
    Color: "Maroon",
    img: "http://dummyimage.com/597x502.png",
    Category: "Collections",
  },
  {
    id: "11",
    Modelo: "Silverado 1500",
    Marca: "Chevrolet",
    Año: 2011,
    Stock: 16,
    Precio: "$15687.88",
    Color: "Aquamarine",
    img: "http://dummyimage.com/698x552.png",
    Category: "Outlets",
  },
  {
    id: "12",
    Modelo: "B-Series",
    Marca: "Mazda",
    Año: 2002,
    Stock: 10,
    Precio: "$22535.10",
    Color: "Crimson",
    img: "http://dummyimage.com/634x688.png",
    Category: "News",
  },
  {
    id: "13",
    Modelo: "Paseo",
    Marca: "Toyota",
    Año: 1993,
    Stock: 18,
    Precio: "$13081.47",
    Color: "Turquoise",
    img: "http://dummyimage.com/556x543.png",
    Category: "Collections",
  },
  {
    id: "14",
    Modelo: "Expedition",
    Marca: "Ford",
    Año: 2005,
    Stock: 15,
    Precio: "$49119.75",
    Color: "Blue",
    img: "http://dummyimage.com/644x505.png",
    Category: "News",
  },
  {
    id: "15",
    Modelo: "2500",
    Marca: "Chevrolet",
    Año: 1993,
    Stock: 10,
    Precio: "$23350.74",
    Color: "Fuscia",
    img: "http://dummyimage.com/620x607.png",
    Category: "Collections",
  },
  {
    id: "16",
    Modelo: "Precis",
    Marca: "Mitsubishi",
    Año: 1986,
    Stock: 15,
    Precio: "$47295.64",
    Color: "Yellow",
    img: "http://dummyimage.com/700x612.png",
    Category: "Collections",
  },
  {
    id: "17",
    Modelo: "G-Series G20",
    Marca: "Chevrolet",
    Año: 1992,
    Stock: 16,
    Precio: "$41247.47",
    Color: "Orange",
    img: "http://dummyimage.com/610x595.png",
    Category: "News",
  },
  {
    id: "18",
    Modelo: "5 Series",
    Marca: "BMW",
    Año: 1999,
    Stock: 14,
    Precio: "$20807.43",
    Color: "Blue",
    img: "http://dummyimage.com/665x609.png",
    Category: "Outlets",
  },
  {
    id: "19",
    Modelo: "RAV4",
    Marca: "Toyota",
    Año: 2008,
    Stock: 17,
    Precio: "$24239.17",
    Color: "Blue",
    img: "http://dummyimage.com/507x619.png",
    Category: "News",
  },
  {
    id: "20",
    Modelo: "Montana",
    Marca: "Pontiac",
    Año: 2005,
    Stock: 19,
    Precio: "$26533.77",
    Color: "Blue",
    img: "http://dummyimage.com/616x659.png",
    Category: "Outlets",
  },
  {
    id: "21",
    Modelo: "GLK-Class",
    Marca: "Mercedes-Benz",
    Año: 2012,
    Stock: 14,
    Precio: "$25644.35",
    Color: "Orange",
    img: "http://dummyimage.com/552x650.png",
    Category: "News",
  },
  {
    id: "22",
    Modelo: "V8 Vantage",
    Marca: "Aston Martin",
    Año: 2006,
    Stock: 15,
    Precio: "$18247.99",
    Color: "Puce",
    img: "http://dummyimage.com/505x662.png",
    Category: "Outlets",
  },
  {
    id: "23",
    Modelo: "CL-Class",
    Marca: "Mercedes-Benz",
    Año: 2012,
    Stock: 15,
    Precio: "$39761.21",
    Color: "Goldenrod",
    img: "http://dummyimage.com/649x560.png",
    Category: "News",
  },
  {
    id: "24",
    Modelo: "Legacy",
    Marca: "Subaru",
    Año: 1998,
    Stock: 20,
    Precio: "$47859.12",
    Color: "Aquamarine",
    img: "http://dummyimage.com/564x576.png",
    Category: "News",
  },
  {
    id: "25",
    Modelo: "tC",
    Marca: "Scion",
    Año: 2008,
    Stock: 15,
    Precio: "$11923.31",
    Color: "Green",
    img: "http://dummyimage.com/606x562.png",
    Category: "Collections",
  },
  {
    id: "26",
    Modelo: "Escort",
    Marca: "Ford",
    Año: 2004,
    Stock: 13,
    Precio: "$11535.68",
    Color: "Goldenrod",
    img: "http://dummyimage.com/631x544.png",
    Category: "News",
  },
  {
    id: "27",
    Modelo: "Discovery",
    Marca: "Land Rover",
    Año: 2000,
    Stock: 16,
    Precio: "$16321.60",
    Color: "Aquamarine",
    img: "http://dummyimage.com/559x551.png",
    Category: "Collections",
  },
  {
    id: "28",
    Modelo: "B9 Tribeca",
    Marca: "Subaru",
    Año: 2006,
    Stock: 19,
    Precio: "$43800.10",
    Color: "Green",
    img: "http://dummyimage.com/501x648.png",
    Category: "News",
  },
  {
    id: "29",
    Modelo: "Envoy",
    Marca: "GMC",
    Año: 2008,
    Stock: 16,
    Precio: "$41866.01",
    Color: "Goldenrod",
    img: "http://dummyimage.com/619x517.png",
    Category: "Outlets",
  },
  {
    id: "30",
    Modelo: "Grand Caravan",
    Marca: "Dodge",
    Año: 1995,
    Stock: 10,
    Precio: "$12061.18",
    Color: "Khaki",
    img: "http://dummyimage.com/682x596.png",
    Category: "News",
  },
  {
    id: "31",
    Modelo: "Grand Prix",
    Marca: "Pontiac",
    Año: 1997,
    Stock: 18,
    Precio: "$17828.77",
    Color: "Fuscia",
    img: "http://dummyimage.com/584x577.png",
    Category: "Collections",
  },
  {
    id: "32",
    Modelo: "S4",
    Marca: "Audi",
    Año: 2010,
    Stock: 15,
    Precio: "$34655.17",
    Color: "Fuscia",
    img: "http://dummyimage.com/667x520.png",
    Category: "Collections",
  },
  {
    id: "33",
    Modelo: "Imperial",
    Marca: "Chrysler",
    Año: 1926,
    Stock: 11,
    Precio: "$14522.21",
    Color: "Aquamarine",
    img: "http://dummyimage.com/505x607.png",
    Category: "Collections",
  },
  {
    id: "34",
    Modelo: "Xterra",
    Marca: "Nissan",
    Año: 2007,
    Stock: 17,
    Precio: "$24227.92",
    Color: "Blue",
    img: "http://dummyimage.com/606x647.png",
    Category: "Collections",
  },
  {
    id: "35",
    Modelo: "tC",
    Marca: "Scion",
    Año: 2011,
    Stock: 19,
    Precio: "$40694.98",
    Color: "Teal",
    img: "http://dummyimage.com/512x502.png",
    Category: "Outlets",
  },
  {
    id: "36",
    Modelo: "Cavalier",
    Marca: "Chevrolet",
    Año: 1997,
    Stock: 16,
    Precio: "$23184.65",
    Color: "Orange",
    img: "http://dummyimage.com/669x681.png",
    Category: "Outlets",
  },
  {
    id: "37",
    Modelo: "Sable",
    Marca: "Mercury",
    Año: 1986,
    Stock: 20,
    Precio: "$13646.03",
    Color: "Purple",
    img: "http://dummyimage.com/675x643.png",
    Category: "Collections",
  },
  {
    id: "38",
    Modelo: "Venture",
    Marca: "Chevrolet",
    Año: 2005,
    Stock: 17,
    Precio: "$15719.86",
    Color: "Turquoise",
    img: "http://dummyimage.com/500x592.png",
    Category: "Outlets",
  },
  {
    id: "39",
    Modelo: "F250",
    Marca: "Ford",
    Año: 1996,
    Stock: 19,
    Precio: "$14755.51",
    Color: "Indigo",
    img: "http://dummyimage.com/552x691.png",
    Category: "Collections",
  },
  {
    id: "40",
    Modelo: "ES",
    Marca: "Lexus",
    Año: 1998,
    Stock: 11,
    Precio: "$17954.87",
    Color: "Maroon",
    img: "http://dummyimage.com/629x548.png",
    Category: "Outlets",
  },
  {
    id: "41",
    Modelo: "Bravada",
    Marca: "Oldsmobile",
    Año: 1994,
    Stock: 12,
    Precio: "$34226.08",
    Color: "Red",
    img: "http://dummyimage.com/504x639.png",
    Category: "Outlets",
  },
  {
    id: "42",
    Modelo: "F150",
    Marca: "Ford",
    Año: 1995,
    Stock: 16,
    Precio: "$19683.99",
    Color: "Indigo",
    img: "http://dummyimage.com/629x632.png",
    Category: "Collections",
  },
  {
    id: "43",
    Modelo: "Concorde",
    Marca: "Chrysler",
    Año: 1999,
    Stock: 20,
    Precio: "$31837.13",
    Color: "Orange",
    img: "http://dummyimage.com/697x688.png",
    Category: "News",
  },
  {
    id: "44",
    Modelo: "Rally Wagon G3500",
    Marca: "GMC",
    Año: 1996,
    Stock: 14,
    Precio: "$28250.42",
    Color: "Mauv",
    img: "http://dummyimage.com/684x551.png",
    Category: "News",
  },
  {
    id: "45",
    Modelo: "Aurora",
    Marca: "Oldsmobile",
    Año: 2001,
    Stock: 10,
    Precio: "$34511.09",
    Color: "Blue",
    img: "http://dummyimage.com/636x545.png",
    Category: "Collections",
  },
  {
    id: "46",
    Modelo: "Grand Vitara",
    Marca: "Suzuki",
    Año: 2007,
    Stock: 13,
    Precio: "$46222.37",
    Color: "Pink",
    img: "http://dummyimage.com/644x688.png",
    Category: "Collections",
  },
  {
    id: "47",
    Modelo: "Explorer",
    Marca: "Ford",
    Año: 2008,
    Stock: 19,
    Precio: "$46260.94",
    Color: "Aquamarine",
    img: "http://dummyimage.com/580x624.png",
    Category: "Collections",
  },
  {
    id: "48",
    Modelo: "Sierra 3500",
    Marca: "GMC",
    Año: 2010,
    Stock: 17,
    Precio: "$18327.45",
    Color: "Turquoise",
    img: "http://dummyimage.com/523x686.png",
    Category: "News",
  },
  {
    id: "49",
    Modelo: "E-Class",
    Marca: "Mercedes-Benz",
    Año: 2007,
    Stock: 13,
    Precio: "$20840.50",
    Color: "Aquamarine",
    img: "http://dummyimage.com/547x695.png",
    Category: "Outlets",
  },
  {
    id: "50",
    Modelo: "LS",
    Marca: "Lexus",
    Año: 1995,
    Stock: 18,
    Precio: "$25308.47",
    Color: "Pink",
    img: "http://dummyimage.com/601x502.png",
    Category: "Collections",
  },
];
export const getProducts = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(listProducts);
    }, 500);
  });
};

export const getDetailsByid = (id) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(listProducts.find((prod) => prod.id === id));
    }, 500);
  });
};

export const getProductsByCategory = (categoryId) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(listProducts.filter((prod) => prod.Category === categoryId));
    }, 500);
  });
};
